# Generated by Django 4.1 on 2023-08-01 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('place', models.CharField(max_length=30)),
                ('is_online', models.BooleanField()),
                ('is_beginning', models.BooleanField()),
                ('max_students', models.IntegerField()),
            ],
            options={
                'verbose_name': '考试安排',
                'verbose_name_plural': '考试安排',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_ids', models.CharField(max_length=512)),
                ('type', models.IntegerField()),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('question', models.TextField(max_length=1024)),
                ('answer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='ExamOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paid', models.BooleanField()),
                ('payment', models.FloatField()),
                ('pay_time', models.DateField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.student')),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.paper'),
        ),
    ]
